--[[
local window = library:new("脚本名字")
-- 你的脚本名字

local Tab = window:Tab("标签")
-- 左边的标签

local section = Tab:section("分区",true)
 -- true为默认打开，false为默认关闭

section:Textbox("文本框", "", "请输入", function(Value)
    print(Value)
end)
-- 输入文本 Value为输入的内容

section:Button("按钮", function()
    print("Button")
end)
-- 一个按钮点击执行里面的内容

section:Toggle("开关", "", false, function(Value)
    print(Value)
end)
-- 一个开关false为默认关闭，true默认打开，Value为返回值

section:Dropdown("下拉条", '', {"0","1","2","3","4","5","6","7","8","9"}, function(s)
    print(s)
end)
-- 一个下拉条，'{"0","1","2","3","4","5","6","7","8","9"}'为下拉的内容
-- Value为返回值为选择了什么

section:Keybind("键位绑定", Enum.KeyCode.LeftControl, function()
    OpenMain()
end)
-- 一个快捷键，用于电脑，作用为打开或关闭UI

section:Slider("拉条", "", 1, 1, 100, false, function(Value)
    print(Value)
end)
-- 一个能拉动的拉条，Value为数值

section:Label("标签")
-- 一个标签类似于留言]]
local library = loadstring(game:HttpGet("https://raw.githubusercontent.com/10h-pack/UI/refs/heads/main/i6.lua"))()
local window = library:new("6")  local Tab = window:Tab("必知!!!") 
local section = Tab:section("前言必须查看!!!",true)
section:Label("声明")
section:Label("俄亥俄州服务器会导致大部分的脚本消失(别到时候说我脚本不行)")
section:Label("移速或者跳跃不正常的话，请到通用里面的玩家自己进行更改")
section:Label("移动速度=16(不知道对不对👽)跳跃高度=50(不知道对不对😋)")
section:Label("新更新了重力设置,重力可以按照自己的喜好更改(正在研究一键还原)")
section:Label("该脚本为两人合作缝合而成(不全都是缝合)")
section:Label("使用该脚本封号不负责")
section:Label("小白&柳絮联合制作")
section:Label("脚本为免费脚本，请勿拿去圈钱，圈钱的人我操你妈——小白")
section:Label("此脚本是缝合脚本，永久更新")
section:Label("圈钱的人腻湿不湿愁奈拢,大庞茂,窝熙望腻遍乘哒旁冒——柳絮")
local Tab = window:Tab("主要制作")
local section = Tab:section("主要贡献",true)
section:Label("大工程:小白")
section:Label("源码提供布局UI:柳絮")
section:Label("脚本思路:小白")
section:Label("脚本制作:柳絮😋")
section:Label("支持玩家")
section:Label("白金之星(段子)")
section:Label("社交的手腕")
section:Label("👽👽👽👽👽")
local Tab = window:Tab("blair")
local section = Tab:section("blair",false)
section:Button("1", function()
         print("Button")
         loadstring(game:HttpGet('https://raw.githubusercontent.com/MythHubOfficial/Blair/refs/heads/main/MYTHONTOP'))()
         end)
section:Button("2汉化", function()
         print("Button")
loadstring(game:HttpGet("https://raw.githubusercontent.com/wdwahDWGU/DWAHUBUHD/refs/heads/main/MSDUIWQQWD"))()         
         end)
local Tab = window:Tab("指令挂")
local section = Tab:section("ly",false)
section:Button("ly", function()
         print("Button")
loadstring(game:HttpGet(('https://raw.githubusercontent.com/EdgeIY/infiniteyield/master/source'),true))()         
         end)
section:Label("bang能够掀人")
section:Label("noface没有脸")
section:Label("headsit坐在玩家头上加玩家名字")
section:Label("float悬浮")
section:Label("re重置人物但位置不变")
section:Label("dance跳舞")
section:Label("nolegs没有腿")
section:Label("bring+玩家名字可以让玩家吸到你手上但是只能用于一些服务器")
section:Label("carpet趴着走")
section:Label("infjump无限跳跃")
section:Label("xray透视地图物体变透明")
section:Label("noanim没有动作")
section:Label("spin人物旋转")
section:Label("sitwalk坐着走")
section:Label("trip人物摔倒")
section:Label("antikick防踢")
section:Label("lay躺下")
section:Label("sit坐")
section:Label("god加血")
section:Label("goto+玩家名字传送")
section:Label("所有需要加目标的指令中间必须要空格，不然不能使用")
section:Label("me=自己")
local Tab = window:Tab("通用")
local section = Tab:section("玩家传送", false)

-- 获取所有玩家名字作为下拉选项
local playerNames = {}
for _, player in pairs(game.Players:GetPlayers()) do
    table.insert(playerNames, player.Name)
end

section:Dropdown("下拉条", '', playerNames, function(selectedPlayerName)
    local targetPlayer = game.Players:FindFirstChild(selectedPlayerName)
    if targetPlayer and targetPlayer.Character and targetPlayer.Character:FindFirstChild("HumanoidRootPart") then
        local localPlayer = game.Players.LocalPlayer
        if localPlayer.Character and localPlayer.Character:FindFirstChild("HumanoidRootPart") then
            localPlayer.Character.HumanoidRootPart.CFrame = targetPlayer.Character.HumanoidRootPart.CFrame
        end
    end
end)

local section = Tab:section("玩家更改",false)         
section:Slider("跳跃高度", "", 50, 50, 400, false, function(Value)
     print(Value)
game.Players.LocalPlayer.Character.Humanoid.JumpPower = Value  
  end)
section:Slider("移动速度", "", 16, 16, 400, false, function(Value)
     print(Value)
game.Players.LocalPlayer.Character.Humanoid.WalkSpeed = Value
              end)
section:Slider("焦距", "", 70, 1, 120, false, function(Value)
     print(Value)
Workspace.Camera.FieldOfView = Value
              end)
local section = Tab:section("夜视",false)
section:Toggle("开关", "", false, function(Value)
    print(Value)
    if Value then
        game.Lighting.Ambient = Color3.new(1, 1, 1)
    else
        game.Lighting.Ambient = Color3.new(0, 0, 0)
    end
end)
local section = Tab:section("飞行",false)
section:Button("飞行(速度够快，可以穿墙)", function()
         print("Button")
loadstring("\108\111\97\100\115\116\114\105\110\103\40\103\97\109\101\58\72\116\116\112\71\101\116\34\104\116\116\112\115\58\47\47\112\97\115\116\101\98\105\110\46\99\111\109\47\114\97\119\47\83\76\120\100\97\75\112\119\34\41\40\41\10")()
         end)
local section = Tab:section("死亡笔记本",false)
section:Button("死亡笔记本", function()
         print("Button")
loadstring(game:HttpGet("https://raw.githubusercontent.com/krlpl/dfhj/main/%E6%AD%BB%E4%BA%A1%E7%AC%94%E8%AE%B0.txt"))()         
         end)
local section = Tab:section("子追(有的服务器不能用)",false)
section:Button("子追", function()
         print("Button")
loadstring(game:HttpGet("https://pastebin.com/raw/1AJ69eRG"))()         
         end)
local section = Tab:section("飞车(自然灾害和造船寻宝不要用)",false)
section:Button("飞车", function()
         print("Button")
loadstring(game:HttpGet("https://pastebin.com/raw/63T0fkBm"))()         
         end)
local section = Tab:section("无限跳",false)
section:Button("无限跳", function()
         print("Button")
loadstring(game:HttpGet("https://pastebin.com/raw/V5PQy3y0", true))()         
         end)
local section = Tab:section("自杀(函数)",false)
section:Button("自杀", function()
         print("Button")
game.Players.LocalPlayer.Character.Humanoid.Health=0         
         end)
local section = Tab:section("Anti-AFK",false)
section:Button("Anti-AFK", function()
         print("Button")
loadstring(game:HttpGet("https://pastebin.com/raw/9fFu43FF"))()         
         end)
local section = Tab:section("键盘",false)
section:Button("键盘", function()
         print("Button")
loadstring(game:HttpGet("https://raw.githubusercontent.com/advxzivhsjjdhxhsidifvsh/mobkeyboard/main/main.txt"))()                
         end)
local section = Tab:section("光影",false)
section:Button("光影", function()
         print("Button")
loadstring(game:HttpGet("https://pastebin.com/raw/jHBfJYmS"))()
end)
local Tab = window:Tab("dex和spy")                        local section = Tab:section("dex",false)
section:Button("dex1", function()
         print("Button")
loadstring(game:HttpGet("https://raw.githubusercontent.com/infyiff/backup/main/dex.lua"))()                
         end) 
section:Button("dex2", function()
         print("Button")
loadstring(game:HttpGet("https://raw.githubusercontent.com/IlIlIlIlIlIlIlIlIlIlIlIlIlIlIlIl/Script/main/Tools/DarkDexV3.txt", true))()          end)
local section = Tab:section("spy",false)
section:Button("spy1", function()
         print("Button")
getgenv().Spy="汉化Spy" loadstring(game:HttpGet("https://raw.githubusercontent.com/xiaopi77/xiaopi77/refs/heads/main/spy%E6%B1%89%E5%8C%96%20(1).txt"))()
         end)
local Tab = window:Tab("战争大亨")
local section = Tab:section("剑客",false)
section:Button("剑客", function()
           print("Button")
Sword_Guest_V7 = "欢迎使用剑客V7"	
Sword_Guest__V7 = "作者_初夏"	
Sword_Guest___V7 = "剑客QQ群155160100"	
loadstring(game:HttpGet("https://raw.githubusercontent.com/Zer0neK/Hello/refs/heads/main/SG-V7"))()
 end)

local Tab = window:Tab("doors")
local section = Tab:section("生成rush",false)
section:Button("生成rush", function()
         print("Button")
loadstring(game:HttpGet("https://rawscripts.net/raw/DOORS-Custom-Entity-S*er-V2-21705"))()
         end)                                                                                                   local section = Tab:section("mspaintXK汉",false)
section:Button("mspaintXK汉化", function()
         print("Button")
loadstring(game:HttpGet("https://raw.githubusercontent.com/XiaoXuAnZang/XKscript/refs/heads/main/DOORS.txt"))()
         end)
local section = Tab:section("十字架",false)
section:Button("十字架", function()
         print("Button")
loadstring(game:HttpGet("https://pastebin.com/raw/FCSyG6Th"))()
         end)
local section = Tab:section("夜视仪",false)
section:Button("夜视仪", function()
         print("Button")
loadstring(game:HttpGet("https://pastebin.com/raw/4Vsv1Xwn"))()
         end)                                                                                   local Tab = window:Tab("速度传奇")
local section = Tab:section("1",false)
section:Button("1", function()
         print("Button")
loadstring(game:HttpGet('\104\116\116\112\115\58\47\47\114\97\119\46\103\105\116\104\117\98\117\115\101\114\99\111\110\116\101\110\116\46\99\111\109\47\98\111\121\115\99\112\47\98\101\116\97\47\109\97\105\110\47\37\69\57\37\56\48\37\57\70\37\69\53\37\66\65\37\65\54\37\69\55\37\56\50\37\66\56\37\69\56\37\66\53\37\66\55\46\108\117\97'))()
         end)
local Tab = window:Tab("造船寻宝")
local section = Tab:section("刷钱",false)
section:Button("刷钱", function()
         print("Button")
loadstring(game:HttpGet("https://pastebin.com/raw/Lyy77rnr",true))()         
         end)
local Tab = window:Tab("evade")
local section = Tab:section("1",false)
section:Button("1", function()
         print("Button")
loadstring(game:HttpGet('https://raw.githubusercontent.com/9Strew/roblox/main/gamescripts/evade.lua'))()         
         end)
local section = Tab:section("2",false)
section:Button("2", function()
         print("Button")
loadstring(game:HttpGet("https://raw.githubusercontent.com/GamingScripter/Darkrai-X/main/Games/Evade"))()        
         end)
local Tab = window:Tab("SBC")         
local section = Tab:section("1",false)
section:Button("1", function()
         print("Button")
loadstring(game:HttpGet("https://raw.githubusercontent.com/10h-pack/345upd/refs/heads/main/SSBC.lua"))()        
         end)
local Tab = window:Tab("周五夜放克")    
local section = Tab:section("1",false)
section:Button("1", function()
         print("Button")
loadstring(game:HttpGet("https://raw.githubusercontent.com/wally-rblx/funky-friday-autoplay/main/main.lua",true))()      
         end)
local Tab = window:Tab("餐厅大亨")
local section = Tab:section("1",false)
section:Button("1", function()
         print("Button")
loadstring(game:HttpGet("https://rawscripts.net/raw/LUXURY-ITEMS-Restaurant-Tycoon-2-OP-AutoFarm-9904"))()        
         end)  
local section = Tab:section("2",false)
section:Button("2", function()
         print("Button")
loadstring(game:HttpGet(('https://raw.githubusercontent.com/bloodball/-back-ups-for-libs/main/wall%20v3')))()        
         end)
local Tab = window:Tab("伐木大亨2")
local section = Tab:section("白脚本",false)
section:Button("白脚本", function()
         print("Button")
loadstring(game:HttpGet("https://raw.githubusercontent.com/noob616161/KphoooOooooOoOo-wprfbdksorbfKvsdcIUH-194jddJ-___-_-lIlIIIllIIIlllIIIIlIlIIlIllIIIllllllIllllllIIIl/main/bai/%E4%BC%90%E6%9C%A8"))()        
         end)
local Tab = window:Tab("luaware汉化")
local section = Tab:section("luaware汉化",false)
section:Button("luaware汉化", function()
         print("Button")
loadstring(game:HttpGet("https://raw.githubusercontent.com/XiaoYunCN/UWU/main/LuaWare.lua", true))()                      end)
local Tab = window:Tab("更多脚本")
local section = Tab:section("皮脚本",false)
section:Button("皮脚本", function()
         print("Button")
getgenv().XiaoPi="皮脚本QQ群1002100032" loadstring(game:HttpGet("https://raw.githubusercontent.com/xiaopi77/xiaopi77/main/QQ1002100032-Roblox-Pi-script.lua"))()
         end)
local section = Tab:section("落叶中心",false)
section:Button("落叶中心", function()
         print("Button")
getgenv().LS="落叶中心" loadstring(game:HttpGet("https://raw.githubusercontent.com/krlpl/Deciduous-center-LS/main/%E8%90%BD%E5%8F%B6%E4%B8%AD%E5%BF%83%E6%B7%B7%E6%B7%86.txt"))()
         end)         